---
- name: install setup run ansible awx
  hosts: all
  become: true
  roles:
   - awx-install
   - awx-setup
   - awx-run
  tasks:
   - name: echo completion
     shell: echo "playbook finished running" 
