---

- name: create python virtualenv
  command: "virtualenv {{virtualenv_location}}"

- name: clone repo
  git:
    repo: git@github.com:ansible/awx.git
    dest: "{{virtualenv_location}}/awx"
    accept_hostkey: yes
