---

- name: check python
  raw: test -e /usr/bin/python
  changed_when: false
  failed_when: false
  register: check_python

- name: install python
  raw: yum -y nstall python
  when: check_python.rc != 0

- name: install pip
  package:
    name: python-pip
    state: present

- name: install virtualenv
  pip:
    name: virtualenv

- name: create python virtualenv with proper
  pip:
    name:
     - python-pip 
     - docker-compose
    state: present
    virtualenv: "{{virtualenv_location}}"

# - name: clone repo
#  git:
#    repo: git@github.com:ansible/awx.git
#    dest: "{{virtualenv_location}}/awx"
#    accept_hostkey: yes
