---

- name: create python virtualenv
  pip:
    virtualenv: "{{virtualenv_location}}/awxenv"
    virtualenv_command: /usr/local/bin/virtualenv

- name: clone repo
  git:
    repo: git@github.com:ansible/awx.git
    dest: "{{virtualenv_location}}/awx"
    accept_hostkey: yes
