---

- name: create python virtualenv
  command: /usr/local/bin/virtualenv "{{virtualenv_location}}/awxenv"

- name: clone repo
  git:
    repo: git@github.com:ansible/awx.git
    dest: "{{virtualenv_location}}/awx"
    accept_hostkey: yes
