---

- name: check python
  raw: test -e /usr/bin/python
  changed_when: false
  failed_when: false
  register: check_python

- name: install python
  raw: yum -y nstall python
  when: check_python.rc != 0

- name: install virtualenv
  pip:
    name: virtualenv

- name: create python virtualenv
  pip:
    name: docker-compose
    virtualenv: "{{virtualenv_location}}/awxenv"

- name: clone repo
  git:
    repo: git@github.com:ansible/awx.git
    dest: "{{virtualenv_location}}/awx"
    accept_hostkey: yes
