---

- name: check python
  raw: test -e /usr/bin/python
  changed_when: false
  failed_when: false
  register: check_python

- name: install python
  raw: yum -y install python
  when: check_python.rc != 0

- name: install pip
  package:
    name: python-pip
    state: present

# do when docker -v doesnt exist
- name: get docker
  command: curl -sSL https://get.docker.com/ | sh

# Do when node -v and npm -v dont exist
- name: yum install make
  command: yum install -y gcc-c++ make

- name: get stable release nodejs
  command: curl -sL https://rpm.nodesource.com/setup_12.x | sudo -E bash -

- name: install nodejs
  command: yum install nodejs

- name: install docker-compose
  pip:
    name: docker-compose
    state: present

# do if repo isnt already clones
- name: clone repo
  git:
    repo: git@github.com:ansible/awx.git
    dest: "{{awx_location}}/awx"
    accept_hostkey: yes

- name: edit awxcompose location
  lineinfile:
    path: "{{awx_location}}/awx/installer/inventory"
    regexp: '^docker_compose_dir='
    line: "docker_compose_dir={{awxcompose_location}}"

- name: edit pgdocker location
  lineinfile:
    path: "{{awx_location}}/awx/installer/inventory"
    regexp: '^postgres_data_dir='
    line: "postgres_data_dir={{pgdocker_location}}"

- name: run the installer
  command: "ansible-playbook -i {{awx_location}}/awx/installer/inventory {{awx_location}}/awx/installer/install.yml"
