---

- name: check python
  raw: test -e /usr/bin/python
  changed_when: false
  failed_when: false
  register: check_python

- name: install python
  raw: yum -y install python
  when: check_python.rc != 0

- name: install pip
  package:
    name: python-pip
    state: present

- name: install docker-compose
  pip:
    name: docker-compose
    state: present

- name: clone repo
  git:
    repo: git@github.com:ansible/awx.git
    dest: "{{awx_location}}/awx"
    accept_hostkey: yes

- name: edit awxcompose location
  lineinfile:
    path: "{{awx_location}}/awx/installer/inventory"
    regexp: '^docker_compose_dir='
    line: "docker_compose_dir={{awxcompose_location}}"

- name: edit pgdocker location
  lineinfile:
    path: "{{awx_location}}/awx/installer/inventory"
    regexp: '^postgres_data_dir='
    line: "postgres_data_dir={{pgdocker_location}}"

- name: run the installer
  command: "ansible-playbook -i {{awx_location}}/awx/installer/inventory {{awx_location}}/awx/installer/install.yml"
