---

- name: check if docker awx_task already running
  docker_container_info:
    name: awx_task
  register: awx_task_container

- name: 
  docker_container:
    name: awx_task
    state: absent
  when: awx_task_container.exists

- name: check if docker awx_web already running
  docker_container_info:
    name: awx_web
  register: awx_web_container

- name: 
  docker_container:
    name: awx_web
    state: absent
  when: awx_web_container.exists

- name: check if docker awx_rabbitmq already running
  docker_container_info:
    name: awx_rabbitmq
  register: awx_rabbitmq_container

- name: 
  docker_container:
    name: awx_rabbitmq
    state: absent
  when: awx_rabbitmq_container.exists

- name: check if docker awx_memcached already running
  docker_container_info:
    name: awx_memcached
  register: awx_memcached_container

- name: 
  docker_container:
    name: awx_memcached
    state: absent
  when: awx_memcached_container.exists

- name: run the ansible awx installer
  command: "ansible-playbook -i inventory install.yml"
  args:
    chdir: "{{awx_location}}/installer"