---

- name: check if docker awx_task already running
  shell: docker ps -a | grep awx_task | wc -l
  register: awx_task_container

- name: stop awx_task
  command: docker stop awx_task
  when: awx_task_container.stdout|int == 1 

- name: remove awx_task
  command: docker rm awx_task
  when: awx_task_container.stdout|int == 1 

- name: check if docker awx_web already running
  shell: docker ps -a | grep awx_web | wc -l
  register: awx_web_container

- name: stop awx_web
  command: docker stop awx_web
  when: awx_web.stdout|int == 1 

- name: remove awx_web
  command: docker rm awx_web
  when: awx_web_container.stdout|int == 1 

- name: check if docker awx_rabbitmq already running
  shell: docker ps -a | grep awx_rabbitmq | wc -l
  register: awx_rabbitmq_container

- name: stop awx_rabbitmq
  command: docker stop awx_rabbitmq
  when: awx_rabbitmq_container.stdout|int == 1 

- name: remove awx_rabbitmq
  command: docker rm awx_rabbitmq
  when: awx_rabbitmq_container.stdout|int == 1 

- name: check if docker awx_memcached already running
  shell: docker ps -a | grep awx_memcached | wc -l
  register: awx_memcached_container

- name: stop awx_memcached
  command: docker stop awx_memcached
  when: awx_memcached_container.stdout|int == 1 

- name: remove awx_memcached
  command: docker rm awx_memcached
  when: awx_memcached_container.stdout|int == 1 

- name: run the ansible awx installer
  command: "ansible-playbook -i inventory install.yml"
  args:
    chdir: "{{awx_location}}/installer"
    