---

- name: update yum
  raw: yum -y update

- name: install docker
  command: amazon-linux-extras install -y docker

- name: install ansible2
  command: amazon-linux-extras install -y ansible2

- name: install postgresql11
  command: amazon-linux-extras install -y postgresql11

- name: check python installed
  raw: test -e /usr/bin/python
  changed_when: false
  failed_when: false
  register: check_python

- name: install python
  raw: yum -y install python
  when: check_python.rc != 0

- name: download pip
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /get-pip.py

- name: install pip
  command: python /get-pip.py

- name: install docker-compose
  command: pip install —ignore-installed docker-compose

- name: get nvm
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
  args:
    warn: no

- name: run nvm
  command: . ~/.nvm/nvm.sh

- name: install node and npm with nvm
  command: nvm install node
